### ISSUE TITLE
Enable Kubernetes 会安装docker/desktop-kubernetes，无法使用

### ISSUE THREAD

**Issue by AllenZMC** [AliyunContainerService/k8s-for-docker-desktop#100]
Enable Kubernetes 会安装docker/desktop-kubernetes镜像，无法使用项目中的几个镜像，而且显示Kubernetes在运行，但是访问出错
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding`
有大神了解吗？

**Comment by denverdino** [comment]
切换context了吗？
kubectl config use-context docker-desktop

或者选择 Docker 图标，Kubernetes -> 选择相应的集群信息

**Comment by AllenZMC** [comment]
切换了，不行， 开启Kubernetes会自己拉取docker/desktop-kubernetes镜像来启用k8s，而不是使用本项目中预下载的几个k8s镜像， 很奇怪

**Comment by denverdino** [comment]
这是正常的，你配置Docker Engine的Docker Hub mirror了吗？

**Comment by AllenZMC** [comment]
@denverdino  是` "registry-mirrors": [
    "https://docker.mirrors.ustc.edu.cn"
  ]` 这个吗？

**Comment by denverdino** [comment]
如果下载不了，换阿里云的试试，

**Comment by AllenZMC** [comment]
@denverdino      可以下载的， 就是下面这样
`REPOSITORY                                                       TAG                                              IMAGE ID            CREATED             SIZE
docker/desktop-kubernetes                                        kubernetes-v1.16.5-cni-v0.7.5-critools-v1.15.0   a86647f0b376        5 months ago        279MB
k8s.gcr.io/kube-apiserver                                        v1.16.5                                          fc838b21afbb        5 months ago        159MB
k8s.gcr.io/kube-scheduler                                        v1.16.5                                          b4d073a9efda        5 months ago        83.5MB
k8s.gcr.io/kube-proxy                                            v1.16.5                                          0ee1b8a3ebe0        5 months ago        82.7MB
k8s.gcr.io/kube-controller-manager                               v1.16.5                                          441835dd2301        5 months ago        151MB
quay.io/kubernetes-ingress-controller/nginx-ingress-controller   0.26.1                                           29024c9c6e70        9 months ago        483MB
k8s.gcr.io/etcd                                                  3.3.15-0                                         b2756210eeab        10 months ago       247MB
k8s.gcr.io/coredns                                               1.6.2                                            bf261d157914        11 months ago       44.1MB
k8s.gcr.io/pause                                                 3.1                                              da86e6ba6ca1        2 years ago         742kB`

docker Engine 自己下载安装docker/desktop-kubernetes:kubernetes-v1.16.5-cni-v0.7.5-critools-v1.15.0 的镜像，好像不使用k8s.gcr.io的镜像

**Comment by denverdino** [comment]
这个是OK的，Docker自己会有一些镜像进行下载。我们绕开k8s.gcr.io的镜像

**Comment by AllenZMC** [comment]
是代理的额问题，已解决
