### ISSUE TITLE
没有1.19.0

### ISSUE THREAD

**Issue by aogg** [AliyunContainerService/k8s-for-docker-desktop#105]
kubeadm config images pull --image-repository registry.cn-hangzhou.aliyuncs.com/google_containers
W0830 23:19:37.883205   11508 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
failed to pull image "registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.19.0": output: Error response from daemon: manifest for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.19.0 not found: manifest unknown: manifest unknown

**Comment by denverdino** [comment]
hmm

As of Kuberenetes v1.19, Kubernetes container images are stored on a community-controlled storage bucket, located at {asia,eu,us}.gcr.io/k8s-artifacts-prod. The k8s.gcr.io vanity domain has been updated to this new bucket. This brings production artifacts under community control.

我调整一下镜像复制策略

**Comment by denverdino** [comment]
Fixed in https://github.com/AliyunContainerService/sync-repo/pull/9

**Comment by aogg** [comment]
kubeadm config images pull --image-repository registry.cn-hangzhou.aliyuncs.com/google_containers
