### ISSUE TITLE
Kubernetes 1.18.8 无法正常启动

### ISSUE THREAD

**Issue by quanzaiyu** [AliyunContainerService/k8s-for-docker-desktop#107]
1. 下载的Docker Desktop版本为：

![](https://kan.xiaoyulive.top/bug/004.png)

若图片无法正常显示，请查看 [https://kan.xiaoyulive.top/bug/004.png](https://kan.xiaoyulive.top/bug/004.png)

2. 通过master分支，在Powershell中执行脚本拉取相关镜像，发现镜像拉取成功

![](https://kan.xiaoyulive.top/bug/001.png)

若图片无法正常显示，请查看 [https://kan.xiaoyulive.top/bug/001.png](https://kan.xiaoyulive.top/bug/001.png)

3. 启动Kubernetes，检查容器，已经处于运行状态：

![](https://kan.xiaoyulive.top/bug/002.png)

若图片无法正常显示，请查看 [https://kan.xiaoyulive.top/bug/002.png](https://kan.xiaoyulive.top/bug/002.png)

4. 发现一直处于starting状态：

![](https://kan.xiaoyulive.top/bug/003.png)

若图片无法正常显示，请查看 [https://kan.xiaoyulive.top/bug/003.png](https://kan.xiaoyulive.top/bug/003.png)

---

重启Docker和重启计算机均已试过，删除.kube文件夹也试过，均不起效，还是处于starting状态。

**Comment by ironman1987** [comment]
> 1. 下载的Docker Desktop版本为：
> 
> ![](https://camo.githubusercontent.com/fff8d2526628d03ce239d69232cfc80d48221391/68747470733a2f2f6b616e2e7869616f79756c6976652e746f702f6275672f3030342e706e67)
> 
> 若图片无法正常显示，请查看 https://kan.xiaoyulive.top/bug/004.png
> 
> 1. 通过master分支，在Powershell中执行脚本拉取相关镜像，发现镜像拉取成功
> 
> ![](https://camo.githubusercontent.com/765fff8537c63fea7c82562db2b3d42363700773/68747470733a2f2f6b616e2e7869616f79756c6976652e746f702f6275672f3030312e706e67)
> 
> 若图片无法正常显示，请查看 https://kan.xiaoyulive.top/bug/001.png
> 
> 1. 启动Kubernetes，检查容器，已经处于运行状态：
> 
> ![](https://camo.githubusercontent.com/9bf091afe8bdfbd766824cb9e3a5e0177b453ca4/68747470733a2f2f6b616e2e7869616f79756c6976652e746f702f6275672f3030322e706e67)
> 
> 若图片无法正常显示，请查看 https://kan.xiaoyulive.top/bug/002.png
> 
> 1. 发现一直处于starting状态：
> 
> ![](https://camo.githubusercontent.com/7a4947e59aa43b5effd6e4fa3506197fdc0b1c0d/68747470733a2f2f6b616e2e7869616f79756c6976652e746f702f6275672f3030332e706e67)
> 
> 若图片无法正常显示，请查看 https://kan.xiaoyulive.top/bug/003.png
> 
> 重启Docker和重启计算机均已试过，删除.kube文件夹也试过，均不起效，还是处于starting状态。

我也是和这位一样的版本，一样的问题

**Comment by denverdino** [comment]
感觉K8s已经启动起来了，你们的Docker Registry Mirror是否配置了？还需要从Docker Hub下载几个镜像

**Comment by ironman1987** [comment]
> 感觉K8s已经启动起来了，你们的Docker Registry Mirror是否配置了？还需要从Docker Hub下载几个镜像

已经改为了阿里的Docker Registry Mirror。还需要下载别的什么镜像吗？一直是starting....

**Comment by denverdino** [comment]
看一下相关镜像是否都已经下载了

```
$ docker images
REPOSITORY                                                       TAG                                              IMAGE ID            CREATED             SIZE
docker/desktop-kubernetes                                        kubernetes-v1.18.8-cni-v0.8.5-critools-v1.17.0   e777077bd5d8        5 weeks ago         292MB
k8s.gcr.io/kube-proxy                                            v1.18.8                                          0fb7201f92d0        6 weeks ago         117MB
k8s.gcr.io/kube-apiserver                                        v1.18.8                                          92d040a0dca7        6 weeks ago         173MB
k8s.gcr.io/kube-controller-manager                               v1.18.8                                          6a979351fe5e        6 weeks ago         162MB
k8s.gcr.io/kube-scheduler                                        v1.18.8                                          6f7135fb47e0        6 weeks ago         95.3MB
docker/desktop-storage-provisioner                               v1.1                                             e704287ce753        6 months ago        41.8MB
docker/desktop-vpnkit-controller                                 v1.0                                             79da37e5a3aa        7 months ago        36.6MB
k8s.gcr.io/pause                                                 3.2                                              80d28bedfe5d        7 months ago        683kB
k8s.gcr.io/coredns                                               1.6.7                                            67da37a9a360        8 months ago        43.8MB
k8s.gcr.io/etcd                                                  3.4.3-0                                          303ce5db0e90        11 months ago       288MB
quay.io/kubernetes-ingress-controller/nginx-ingress-controller   0.26.1                                           29024c9c6e70        12 months ago       483MB
```

**Comment by ironman1987** [comment]
这是.\load_images.ps1 运行完下载的镜像。springio/gs-spring-boot-docker，redis是我个人使用镜像。
![image](https://user-images.githubusercontent.com/5051241/94508471-9ec9f780-0244-11eb-8a3c-02308945d368.png)

**Comment by ironman1987** [comment]
> 看一下相关镜像是否都已经下载了
> 
> ```
> $ docker images
> REPOSITORY                                                       TAG                                              IMAGE ID            CREATED             SIZE
> docker/desktop-kubernetes                                        kubernetes-v1.18.8-cni-v0.8.5-critools-v1.17.0   e777077bd5d8        5 weeks ago         292MB
> k8s.gcr.io/kube-proxy                                            v1.18.8                                          0fb7201f92d0        6 weeks ago         117MB
> k8s.gcr.io/kube-apiserver                                        v1.18.8                                          92d040a0dca7        6 weeks ago         173MB
> k8s.gcr.io/kube-controller-manager                               v1.18.8                                          6a979351fe5e        6 weeks ago         162MB
> k8s.gcr.io/kube-scheduler                                        v1.18.8                                          6f7135fb47e0        6 weeks ago         95.3MB
> docker/desktop-storage-provisioner                               v1.1                                             e704287ce753        6 months ago        41.8MB
> docker/desktop-vpnkit-controller                                 v1.0                                             79da37e5a3aa        7 months ago        36.6MB
> k8s.gcr.io/pause                                                 3.2                                              80d28bedfe5d        7 months ago        683kB
> k8s.gcr.io/coredns                                               1.6.7                                            67da37a9a360        8 months ago        43.8MB
> k8s.gcr.io/etcd                                                  3.4.3-0                                          303ce5db0e90        11 months ago       288MB
> quay.io/kubernetes-ingress-controller/nginx-ingress-controller   0.26.1                                           29024c9c6e70        12 months ago       483MB
> ```

这是.\load_images.ps1 运行完下载的镜像。springio/gs-spring-boot-docker，redis是我个人使用镜像。
![image](https://user-images.githubusercontent.com/5051241/94508662-084a0600-0245-11eb-8d14-1c80a78a8f17.png)

**Comment by denverdino** [comment]
应该是Docker Registry Mirror没有生效，有些镜像没有拉下来。

**Comment by ironman1987** [comment]
@denverdino 这是下载日志
PS F:\xx\k8s-for-docker-desktop> .\load_images.ps1
k8s.gcr.io/pause:3.2=registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2
3.2: Pulling from google_containers/pause
Digest: sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2
registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/pause@sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108
k8s.gcr.io/kube-controller-manager:v1.18.8=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.18.8
v1.18.8: Pulling from google_containers/kube-controller-manager
Digest: sha256:1ce5115da0156ffaf2a0651f20e205a351220fc2b2600fdb143a805cd207d4af
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.18.8
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.18.8
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.18.8
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager@sha256:1ce5115da0156ffaf2a0651f20e205a351220fc2b2600fdb143a805cd207d4af
k8s.gcr.io/kube-scheduler:v1.18.8=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.18.8
v1.18.8: Pulling from google_containers/kube-scheduler
Digest: sha256:9254ddc774794e5c680967254e7c64c14f6b7fe820f02393d65a9d3d0d281db3
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.18.8
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.18.8
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.18.8
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler@sha256:9254ddc774794e5c680967254e7c64c14f6b7fe820f02393d65a9d3d0d281db3
k8s.gcr.io/kube-proxy:v1.18.8=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.18.8
v1.18.8: Pulling from google_containers/kube-proxy
Digest: sha256:8d84b97dbac353686e9bdc10ae7e85f59558399ae0949e7a46c1c5a56e321079
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.18.8
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.18.8
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.18.8
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy@sha256:8d84b97dbac353686e9bdc10ae7e85f59558399ae0949e7a46c1c5a56e321079
k8s.gcr.io/kube-apiserver:v1.18.8=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.18.8
v1.18.8: Pulling from google_containers/kube-apiserver
Digest: sha256:4fd1a6d25b5fe5db3647ed1d368c671b618efafb6ddbe06fc64697d2ba271aa9
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.18.8
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.18.8
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.18.8
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver@sha256:4fd1a6d25b5fe5db3647ed1d368c671b618efafb6ddbe06fc64697d2ba271aa9
k8s.gcr.io/etcd:3.4.3-0=registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.4.3-0
3.4.3-0: Pulling from google_containers/etcd
Digest: sha256:4198ba6f82f642dfd18ecf840ee37afb9df4b596f06eef20e44d0aec4ea27216
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.4.3-0
registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.4.3-0
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.4.3-0
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/etcd@sha256:4198ba6f82f642dfd18ecf840ee37afb9df4b596f06eef20e44d0aec4ea27216
k8s.gcr.io/coredns:1.6.7=registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:1.6.7
1.6.7: Pulling from google_containers/coredns
Digest: sha256:695a5e109604331f843d2c435f488bf3f239a88aec49112d452c1cbf87e88405
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:1.6.7
registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:1.6.7
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:1.6.7
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/coredns@sha256:695a5e109604331f843d2c435f488bf3f239a88aec49112d452c1cbf87e88405
quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.26.1=registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:0.26.1
0.26.1: Pulling from google_containers/nginx-ingress-controller
Digest: sha256:5da1b2e84ecbdb27facbea84bc6ddc9d50145d824963230735b47828891cba7b
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:0.26.1
registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:0.26.1
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:0.26.1
Untagged: registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller@sha256:5da1b2e84ecbdb27facbea84bc6ddc9d50145d824963230735b47828891cba7b

**Comment by denverdino** [comment]
Docker Hub的镜像我们没有做特殊处理，理论上配置了Docker Hub mirror应该可以解决。
可以试着重启一下docker engine, 然后试一下如下命令，看看是否mirror配置生效

```
docker pull docker/desktop-storage-provisioner:v1.1
```

**Comment by ironman1987** [comment]
@denverdino 这个是按照你说的执行的
![image](https://user-images.githubusercontent.com/5051241/94517890-78fc1d00-025b-11eb-8cfd-335c16d50e7d.png)

**Comment by ironman1987** [comment]
@denverdino 已手动下载你所有的镜像，但是还是处于starting中
![image](https://user-images.githubusercontent.com/5051241/94631362-d4c9b300-02fa-11eb-8879-f22670e1b64a.png)
![Uploading image.png…]()

**Comment by ironman1987** [comment]
@denverdino 已手动下载你所有的镜像，但是还是处于starting中
![image](https://user-images.githubusercontent.com/5051241/94631410-ffb40700-02fa-11eb-82c5-6a2e59129aef.png)
![image](https://user-images.githubusercontent.com/5051241/94631428-0e022300-02fb-11eb-92a3-d5268cc670c6.png)

**Comment by ironman1987** [comment]
@denverdino 告诉你好消息，已经解决了。
1、如果没有下载完全，手动下载你提供的镜像及版本。
2、C:\Windows\System32\drivers\etc\hosts加入# Kubernetes
127.0.0.1 kubernetes.docker.internal配置，然后启动docker kubernetes
![image](https://user-images.githubusercontent.com/5051241/94633986-6d633180-0301-11eb-9c9d-bf59bff04663.png)

**Comment by denverdino** [comment]
辛苦了，很奇怪的问题。也许和Docker Desktop for Windows相关。多谢告知

**Comment by haoxd** [comment]
![image](https://user-images.githubusercontent.com/18690504/97273361-39325080-186e-11eb-961e-0673e29d0f7f.png)
![image](https://user-images.githubusercontent.com/18690504/97273388-40f1f500-186e-11eb-9fd8-8cd76f810495.png)
![image](https://user-images.githubusercontent.com/18690504/97273421-4a7b5d00-186e-11eb-91a8-44de44e3f9a5.png)
![image](https://user-images.githubusercontent.com/18690504/97273505-6e3ea300-186e-11eb-94b0-6cee2f14f071.png)
重新拉取了和上面一样的镜像，配置了hosts文件，重新启动docker-desktop。重启电脑，还是一直starting
![image](https://user-images.githubusercontent.com/18690504/97273625-94fcd980-186e-11eb-9a46-ed5e871a2957.png)

**Comment by haoxd** [comment]
C:\ProgramData\DockerDesktop  service.txt 文件

Version: 2.4.0.0 (48506)
Channel: stable
Sha1: b18c8c862baf6c395898f15dd01857d96ddca564
Started on: 2020/10/27 15:39:35.472
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Home China
Edition: CoreCountrySpecific
Id: 1903
Build: 18362
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
File: C:\ProgramData\DockerDesktop\service.txt
CommandLine: "C:\Program Files\Docker\Docker\com.docker.service"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:39:35.724][DockerService     ][Info   ] Starting service
[15:40:08.057][LoggingMessageHandler][Info   ] [f70aeb6d] <Server start> GET http://localhost/version
[15:40:08.153][LoggingMessageHandler][Info   ] [f70aeb6d] <Server end> GET http://localhost/version -> 200 OK (took 88ms)
[15:40:08.288][LoggingMessageHandler][Info   ] [77fec8f1] <Server start> GET http://localhost/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[15:40:08.289][ComponentVersions ][Info   ] Edition community
[15:40:08.332][LoggingMessageHandler][Info   ] [77fec8f1] <Server end> GET http://localhost/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 55ms)
[15:40:08.359][LoggingMessageHandler][Info   ] [a2b1bcc4] <Server start> POST http://localhost/migrate/app
[15:40:08.359][LoggingMessageHandler][Info   ] [a2b1bcc4] <Server end> POST http://localhost/migrate/app -> 204 NoContent (took 2ms)
[15:40:08.435][LoggingMessageHandler][Info   ] [d8d88d57] <Server start> POST http://localhost/versionpack/enable
[15:40:08.546][LoggingMessageHandler][Info   ] [d8d88d57] <Server end> POST http://localhost/versionpack/enable -> 204 NoContent (took 111ms)
[15:40:08.556][LoggingMessageHandler][Info   ] [6ef8e2e3] <Server start> POST http://localhost/cloudcli/toggle
[15:40:08.561][LoggingMessageHandler][Info   ] [6ef8e2e3] <Server end> POST http://localhost/cloudcli/toggle -> 204 NoContent (took 5ms)
[15:40:08.648][LoggingMessageHandler][Info   ] [5f7cd686] <Server start> POST http://localhost/dns/refresh-hosts
[15:40:09.166][LoggingMessageHandler][Info   ] [5f7cd686] <Server end> POST http://localhost/dns/refresh-hosts -> 204 NoContent (took 518ms)

**Comment by 1204888712** [comment]
@ironman1987 good job!

**Comment by haoxd** [comment]
注意版本必须一致




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AliyunContainerService/k8s-for-docker-desktop"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月13日(星期五) 中午11:44
收件人:&nbsp;"AliyunContainerService/k8s-for-docker-desktop"<k8s-for-docker-desktop@noreply.github.com&gt;;
抄送:&nbsp;"786436534"<786436534@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [AliyunContainerService/k8s-for-docker-desktop] Kubernetes 1.18.8 无法正常启动 (#107)





 
@ironman1987 good job!

**Comment by kaynePeng** [comment]
我下载了最新的docker 和脚本，还是不行
<img width="463" alt="image" src="https://user-images.githubusercontent.com/46856135/163516990-ba604035-200f-478f-853f-3bc00cc382dc.png">
