### ISSUE TITLE
code": 503

### ISSUE THREAD

**Issue by harryheng** [AliyunContainerService/k8s-for-docker-desktop#122]
访问：http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/
{
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "no endpoints available for service \"kubernetes-dashboard\"",
"reason": "ServiceUnavailable",
"code": 503
}

**Comment by denverdino** [comment]
还没启动吧
