### ISSUE TITLE
Mac docker desktop v3.0.4 , k8s启动失败

### ISSUE THREAD

**Issue by brandChen** [AliyunContainerService/k8s-for-docker-desktop#126]
你好，我mac电脑安装了3.0.4版本的docker desktop 。 按readme步骤执行了并成功下载了相关image，但还是一直在starting状态。
     我注意到，启动k8s的时候会自动pull docker/desktop-kubernetes

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/26214172/105119065-81c67680-5b0a-11eb-88ca-0c066807a8aa.png">
但它启动不了
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/26214172/105119144-b3d7d880-5b0a-11eb-8fa6-fd501b48a6e8.png">

**Comment by denverdino** [comment]
这个应该是Docker镜像没下载下来，重试或者配置mirror

**Comment by brandChen** [comment]
@denverdino 你启动成功了么，方便截个图我看看拢共需要多少镜像么 ：）
