### ISSUE TITLE
Not enough data to create auth info structure

### ISSUE THREAD

**Issue by WeihanLi** [AliyunContainerService/k8s-for-docker-desktop#13]
按照文档 执行 `kubectl proxy` 之后，访问选择 `config` 文件之后登录，出现 `Not enough data to create auth info structure` 的错误

**Comment by denverdino** [comment]
More details? Mac or Windows?

**Comment by WeihanLi** [comment]
windows 10 1803
Docker Desktop Version 2.0.0.0-win81 (29211)

**Comment by denverdino** [comment]
配置一下token（文档已更新）或者跳过即可
