### ISSUE TITLE
想请教下。使用该方式创建的k8s。如何更新一些配置。比如修改kube-apiserver的启动参数。以及k8s相关yaml的位置。环境是Mac

### ISSUE THREAD

**Issue by lWoHvYe** [AliyunContainerService/k8s-for-docker-desktop#130]
环境是Mac OS
创建k8s后，想要修改端口范围。及其他一些配置。网上的方案都是在yaml中调整启动参数。想请教下，使用docker-desktop创建的该如何修改。因为未找到相关的yaml文件。非常感谢
主要是kube-apiserver。
当前需求一个是修改端口范围。要加：- '--service-node-port-range=1-65535'
另一个是nfs共享相关。要添加：- --feature-gates=RemoveSelfLink=false

**Comment by denverdino** [comment]
https://forums.docker.com/t/modifying-the-apiserver-on-kubernetes-on-docker/45857/3
