### ISSUE TITLE
mac docker 21.10.5  ，kubernetes v.1.19.7  启动卡在 starting

### ISSUE THREAD

**Issue by chansanya** [AliyunContainerService/k8s-for-docker-desktop#137]
使用 分支  v.1.19.7 的images.properties 后
![image](https://user-images.githubusercontent.com/47585031/114262254-8fa4dd00-9a11-11eb-97c3-c3a08af2ad80.png)
![image](https://user-images.githubusercontent.com/47585031/114262270-a4817080-9a11-11eb-9826-ee7f82db37b5.png)
 
请问我遗漏了什么呢

**Comment by leihuangyan** [comment]
我查看了历史Issues  新加了
docker/desktop-storage-provisioner:v1.1 
docker/desktop-vpnkit-controller:v1.0
还行不行

**Comment by leihuangyan** [comment]
下载的镜像是需要手动run起来吗

**Comment by chansanya** [comment]
进行 Clean / Purge data  成功了。。
