### ISSUE TITLE
不知道怎么查看所需要的镜像是哪些，求更新最新版的 docker-desktop 2.0.0.2 镜像 

### ISSUE THREAD

**Issue by lluck42** [AliyunContainerService/k8s-for-docker-desktop#14]
RT

**Comment by denverdino** [comment]
前几天已经更新了，git pull 试试？

**Comment by denverdino** [comment]
2.0.0.2 可以用之前的 branch

git checkout 18.09

然后实验

多谢

**Comment by lluck42** [comment]
docker desktop 2.0.0.2 版本 不可用 使用的是 branch 18.09
"Back-off pulling image \"k8s.gcr.io/kube-scheduler-amd64:v1.10.11\"
docker desktop 2.0.1.0 版本 可以用

在 2019-01-21 21:07:55，"朱迪" <lluck42@163.com> 写道：
你好 Li Yi，请问 如何查看 docker desktop 当前版本 所需 kube image 是什么啊？
更新 2.0.1.0 时候总是中断，目前用的是 2.0.0.2 版本，知道 aliyun 有镜像，但是不知道需要哪个

在 2019-01-21 09:54:47，"Li Yi" <notifications@github.com> 写道：


前几天已经更新了，git pull 试试？

**Comment by denverdino** [comment]
k8s.gcr.io/kube-controller-manager-amd64:v1.10.3=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager-amd64:v1.10.3

就是类似的格式，所有镜像我们都同步的

**Comment by lluck42** [comment]
多谢，

在 2019-01-22 12:11:20，"Li Yi" <notifications@github.com> 写道：


k8s.gcr.io/kube-controller-manager-amd64:v1.10.3=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager-amd64:v1.10.3

就是类似的格式，所有镜像我们都同步的

**Comment by denverdino** [comment]
欢迎提PR，我也是业余时间维护一下，不是每个版本都会验证
