### ISSUE TITLE
能否基于该项目搭建一个"由多台机器组成的k8s集群"？

### ISSUE THREAD

**Issue by seeflood** [AliyunContainerService/k8s-for-docker-desktop#141]
请教一下：我有多台笔记本，想搭一个家庭k8s集群，能否给每台机器安装一个k8s-for-docker-desktop，然后让这些机器组成一个k8s集群？
如果不行的话，请教一下有什么别的方案能简单搭建家庭k8s集群么

**Comment by denverdino** [comment]
No, you can try Rancher or some other K8s distro
