### ISSUE TITLE
有1.21.1吗

### ISSUE THREAD

**Issue by h0730303779** [AliyunContainerService/k8s-for-docker-desktop#147]
我苹果是k8s显示1.19.7的 用1.19.7的分支是可以的 

![image](https://user-images.githubusercontent.com/16299810/122327970-5af95880-cf61-11eb-86c0-8d632536ed92.png)

win 一直starting 
切换过1.19.7 也一样不行

**Comment by dmpx** [comment]
也不行，期待...

**Comment by davidwudv** [comment]
same issue

**Comment by dmpx** [comment]
使用以下的映像可以了

 docker pull aiotceo/kube-apiserver:v1.21.1
 docker pull aiotceo/kube-controller-manager:v1.21.1
 docker pull aiotceo/kube-scheduler:v1.21.1
 docker pull aiotceo/kube-proxy:v1.21.1

**Comment by h0730303779** [comment]
> 使用以下的映像可以了
> 
> docker pull aiotceo/kube-apiserver:v1.21.1
> docker pull aiotceo/kube-controller-manager:v1.21.1
> docker pull aiotceo/kube-scheduler:v1.21.1
> docker pull aiotceo/kube-proxy:v1.21.1

我现在就是
![image](https://user-images.githubusercontent.com/16299810/122494128-6446fb80-d01b-11eb-9b6a-b9ba42cebeae.png)

**Comment by dmpx** [comment]
docker pull k8s.gcr.io/coredns/coredns:v1.8.0   # 我主要是这个映像问题，原文档中k8s.gcr.io/coredns:1.8.0 

docker tag aiotceo/kube-apiserver:v1.21.1  k8s.gcr.io/kube-apiserver:v1.21.1

**Comment by WindBruce** [comment]
> 使用以下的映像可以了
> 
> docker pull aiotceo/kube-apiserver:v1.21.1
> docker pull aiotceo/kube-controller-manager:v1.21.1
> docker pull aiotceo/kube-scheduler:v1.21.1
> docker pull aiotceo/kube-proxy:v1.21.1

都这样手动pull了也不行，总有两个起不来

**Comment by WindBruce** [comment]
![image](https://user-images.githubusercontent.com/30388825/122587922-06ed9180-d091-11eb-80af-70067b1f1954.png)

**Comment by dmpx** [comment]
docker/desktop-kubernetes                                        kubernetes-v1.21.1-cni-v0.8.5-critools-v1.17.0-debian   e94f03666724   5 weeks ago     302MB
k8s.gcr.io/kube-apiserver                                        v1.21.1                                                 771ffcf9ca63   5 weeks ago     126MB
k8s.gcr.io/kube-controller-manager                               v1.21.1                                                 e16544fd47b0   5 weeks ago     120MB
k8s.gcr.io/kube-proxy                                            v1.21.1                                                 4359e752b596   5 weeks ago     131MB
k8s.gcr.io/kube-scheduler                                        v1.21.1                                                 a4183b88f6e6   5 weeks ago     50.6MB
docker/desktop-vpnkit-controller                                 v2.0                                                    8c2c38aa676e   6 weeks ago     21MB
docker/desktop-storage-provisioner                               v2.0                                                    99f89471f470   7 weeks ago     41.9MB
k8s.gcr.io/pause                                                 3.4.1                                                   0f8457a4c2ec   5 months ago    683kB
k8s.gcr.io/coredns/coredns                                       v1.8.0                                                  296a6d5035e2   7 months ago    42.5MB
kubernetesui/metrics-scraper                                     v1.0.6                                                  48d79e554db6   8 months ago    34.5MB
k8s.gcr.io/etcd                                                  3.4.13-0                                                0369cf4303ff   9 months ago    253MB
quay.io/kubernetes-ingress-controller/nginx-ingress-controller   0.32.0                                                  70144d369cb2   13 months ago   327MB
jettech/kube-webhook-certgen                                     v1.2.0                                                  b7f5a2787829   19 months ago   49MB

发送自 Windows 10 版邮件应用

发件人: WindBruce
发送时间: 2021年6月18日 23:58
收件人: AliyunContainerService/k8s-for-docker-desktop
抄送: seiya; Comment
主题: Re: [AliyunContainerService/k8s-for-docker-desktop] 有1.21.1吗 (#147)

**Comment by GDongYang** [comment]
同样问题 有解决的吗

**Comment by dmpx** [comment]
@GDongYang 
k8s.gcr.io/pause:3.4.1=registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.4.1
k8s.gcr.io/kube-controller-manager:v1.21.1=aiotceo/kube-controller-manager:v1.21.1
k8s.gcr.io/kube-scheduler:v1.21.1=aiotceo/kube-scheduler:v1.21.1
k8s.gcr.io/kube-proxy:v1.21.1=aiotceo/kube-proxy:v1.21.1
k8s.gcr.io/kube-apiserver:v1.21.1=aiotceo/kube-apiserver:v1.21.1
k8s.gcr.io/etcd:3.4.13-0=registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.4.13-0
k8s.gcr.io/coredns/coredns:v1.8.0=registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:1.8.0
quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.32.0=registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:0.32.0

**Comment by GDongYang** [comment]
这个是docker engine的配置吗

**Comment by GDongYang** [comment]
> registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:0.32.0
是拉这些镜像之后 重新打开docker desktop吗

**Comment by dmpx** [comment]
@GDongYang 步骤和官方文档一样，只是镜像更换了一下

**Comment by dengbinGIt** [comment]
@dmpx 这些镜像是MAc上的吗

**Comment by LLLLLLs** [comment]
![image](https://user-images.githubusercontent.com/26455459/122716698-2a852780-d29d-11eb-8091-3d1dfc6fa3b1.png)
![image](https://user-images.githubusercontent.com/26455459/122716793-4ee10400-d29d-11eb-8a20-ba13dc387f20.png)
![image](https://user-images.githubusercontent.com/26455459/122716837-5d2f2000-d29d-11eb-86b3-73479d0a2d0e.png)
![image](https://user-images.githubusercontent.com/26455459/122716912-7506a400-d29d-11eb-893c-f01939700689.png)
该拉的镜像都拉取了，但还是卡在starting(10min后超时失败)，kube-* & pause & etcd正常启动，其余镜像未见动静，不知道哪里出了问题。

查看了log的Error，发现vpnkit有报错信息：
[09:30:19.768][VpnKit            ][Error  ] vpnkit.exe: Starting to watch : EINVAL
[09:30:19.768][VpnKit            ][Error  ] vpnkit.exe: Failed to watch hosts file : invalid argument
[09:30:19.768][VpnKit            ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
[09:30:19.768][VpnKit            ][Error  ] vpnkit.exe: Pipe.listen: caught (Failure "Failed to connect vmnet device")
不知道是不是这个的原因；

还有就是大量的：
[09:30:37.256][GoBackendProcess  ][Error  ] msg="failed to lookup googlecode.l.googleusercontent.com.: name exists but no relevant records"
[09:31:36.765][GoBackendProcess  ][Error  ] msg="failed to lookup aliregistry.oss-cn-hangzhou.aliyuncs.com.gds.alibabadns.com.: name exists but no relevant records"

**Comment by dmpx** [comment]
@LLLLLLs  
docker tag k8s.gcr.io/coredns:1.8.0 k8s.gcr.io/coredns/coredns:v1.8.0

**Comment by LLLLLLs** [comment]
> coredns:1.8.0 k8s.gcr.io/coredns/cor

ohhhh 就是这个，可以了，感谢，居然悄咪咪改了路径

**Comment by GDongYang** [comment]
> @LLLLLLs
> docker tag k8s.gcr.io/coredns:1.8.0 k8s.gcr.io/coredns/coredns:v1.8.0

Error response from daemon: No such image: k8s.gcr.io/coredns:1.8.0

**Comment by LLLLLLs** [comment]
> > @LLLLLLs
> > docker tag k8s.gcr.io/coredns:1.8.0 k8s.gcr.io/coredns/coredns:v1.8.0
> 
> Error response from daemon: No such image: k8s.gcr.io/coredns:1.8.0

docker pull coredns/coredns:1.8.0
docker tag coredns/coredns:1.8.0 k8s.gcr.io/coredns/coredns:v1.8.0

**Comment by denverdino** [comment]
Just added
