### ISSUE TITLE
k8s一直启动，failed to lookup googlecode.l.googleusercontent.com 

### ISSUE THREAD

**Issue by HueLong** [AliyunContainerService/k8s-for-docker-desktop#152]
![image](https://user-images.githubusercontent.com/37476272/123510113-36f9ed80-d6ac-11eb-8361-b6727f55ea7b.png)

按照教程最后还是一直启动中
log.txt:
![image](https://user-images.githubusercontent.com/37476272/123510167-98ba5780-d6ac-11eb-8b8d-a26756cc9147.png)
service.txt:
![image](https://user-images.githubusercontent.com/37476272/123510194-c0a9bb00-d6ac-11eb-9d6f-17986428e57e.png)
到底为啥呢 我开着vpn呢，但是我尝试开启和关闭 都不行
![image](https://user-images.githubusercontent.com/37476272/123510438-1a5eb500-d6ae-11eb-954e-e63053939de3.png)
![image](https://user-images.githubusercontent.com/37476272/123510653-52b2c300-d6af-11eb-81fb-4ae82d043366.png)
![image](https://user-images.githubusercontent.com/37476272/123510694-8261cb00-d6af-11eb-96f6-9b79d3715f17.png)

**Comment by HueLong** [comment]
用手机热点连接后，报错变为了
![image](https://user-images.githubusercontent.com/37476272/123517178-22c8e700-d6d2-11eb-9b14-e033ea6ea2a9.png)

**Comment by HypSxn** [comment]
老哥，解决 了没，我也碰到这个问题，一直starting，看日志就跟你这个一样，都搞两天了

**Comment by HypSxn** [comment]
我看kube-system这个namespace下的pods,有两个跟coredns相关的容器是ImagePullBackOff状态，是不是因为拉不下来镜像，所以才报上面的错啊

**Comment by HueLong** [comment]
> 老哥，解决 了没，我也碰到这个问题，一直starting，看日志就跟你这个一样，都搞两天了

😂暂时放弃了，改用虚拟机安装k8s了

**Comment by robin-ming** [comment]
我也卡在这里半天了
求解

**Comment by HypSxn** [comment]
老哥，问题解决了，文档中的coredns下载地址有问题，执行下面命令，重启就好了
docker pull coredns/coredns:1.8.0
docker tag coredns/coredns:1.8.0 k8s.gcr.io/coredns/coredns:v1.8.0

**Comment by HueLong** [comment]
![image](https://user-images.githubusercontent.com/37476272/123736477-c2a19300-d8d3-11eb-8743-69ba6331cdd1.png)
不行啊，还是不行
![image](https://user-images.githubusercontent.com/37476272/123736561-e533ac00-d8d3-11eb-9203-6b64e8d7a373.png)

**Comment by HueLong** [comment]
> 老哥，问题解决了，文档中的coredns下载地址有问题，执行下面命令，重启就好了
> docker pull coredns/coredns:1.8.0
> docker tag coredns/coredns:1.8.0 k8s.gcr.io/coredns/coredns:v1.8.0

兄弟 能加个wx不 我的wx：ha_ha__ha_ha

**Comment by Spirit597** [comment]
能建个群吗？大家碰到的问题挺类似的

> > 老哥，问题解决了，文档中的coredns下载地址有问题，执行下面命令，重启就好了
> > docker pull coredns/coredns:1.8.0
> > docker tag coredns/coredns:1.8.0 k8s.gcr.io/coredns/coredns:v1.8.0
> 
> 兄弟 能加个wx不 我的wx：ha_ha__ha_ha

能建个群吗？大家碰到的问题挺类似的

**Comment by HueLong** [comment]
已解决，主要问题是版本问题，大家一定注意版本是否对应

**Comment by InferiorCoder** [comment]
同样的报错
![image](https://user-images.githubusercontent.com/51052388/124390715-6dc0ab00-dd1f-11eb-8e35-14a54b342eb8.png)
是版本的问题 docker desktop中需要的k8s版本要和你下载的是一致的
