### ISSUE TITLE
最新版本不支持1.21.2啊

### ISSUE THREAD

**Issue by helloWordMfy** [AliyunContainerService/k8s-for-docker-desktop#159]

**Comment by dianny123** [comment]
我也遇到这个问题了。
我看最新的更新可以git checkout v1.21.2，
但是链接点进去页面是无效的，是不是还没更新好？
![image](https://user-images.githubusercontent.com/44217134/125413251-926057f0-787b-494c-875c-e21215a626b4.png)

**Comment by outerman** [comment]
我也遇到这个问题，试试master分支，貌似是v1.21.2

**Comment by helloWordMfy** [comment]
切换不过去用git checkout v1.21.2 会说没有相匹配的文件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AliyunContainerService/k8s-for-docker-desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 下午4:41
***@***.***&gt;;
抄送:&nbsp;"一纸荒年 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [AliyunContainerService/k8s-for-docker-desktop] 最新版本不支持1.21.2啊 (#159)





 
我也遇到这个问题，试试master分支，貌似是v1.21.2

**Comment by dianny123** [comment]
> 我也遇到这个问题，试试master分支，貌似是v1.21.2

老哥。你是对的，我刚试了，成功了，谢谢！

**Comment by dianny123** [comment]
> 切换不过去用git checkout v1.21.2 会说没有相匹配的文件
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "AliyunContainerService/k8s-for-docker-desktop" ***@***.***&gt;; 发送时间:&nbsp;2021年7月13日(星期二) 下午4:41 ***@***.***&gt;; 抄送:&nbsp;"一纸荒年 ***@***.******@***.***&gt;; 主题:&nbsp;Re: [AliyunContainerService/k8s-for-docker-desktop] 最新版本不支持1.21.2啊 (#159) 我也遇到这个问题，试试master分支，貌似是v1.21.2 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不用git checout了，直接在master分支上执行 ./load_images.sh

**Comment by denverdino** [comment]
Sorry, fix the branch info
