### ISSUE TITLE
2.0.0.2 stable版本enable kubernetes apply之后，一直starting状态

### ISSUE THREAD

**Issue by JamesLoong** [AliyunContainerService/k8s-for-docker-desktop#16]
Docker Desktop for mac CE 2.0.0.2 stable版本enable kubernetes apply之后，一直starting状态，切换到18.09分支也是一样的问题

**Comment by ccccccmd** [comment]
win10也遇到了这个情况

**Comment by lt94** [comment]
参考这个 PR : https://github.com/AliyunContainerService/k8s-for-docker-desktop/pull/17
