### ISSUE TITLE
docker 3.6 engine 20.10.8 kubernetes v1.21.3 apiserver 启动失败

### ISSUE THREAD

**Issue by panh1992** [AliyunContainerService/k8s-for-docker-desktop#165]
k8s_kube-apiserver_kube-apiserver-docker-desktop_kube-system_***  logs

Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.

I0819 18:14:52.977882       1 server.go:629] external host was not specified, using 192.168.65.4

Error: [service-account-issuer is a required flag, --service-account-signing-key-file and --service-account-issuer are required flags]

**Comment by denverdino** [comment]
Should be fixed. Pls try the v1.21.3 branch
