### ISSUE TITLE
dashboard 登录报错

### ISSUE THREAD

**Issue by jxljf** [AliyunContainerService/k8s-for-docker-desktop#194]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/3088741/164959663-e02525f6-2ade-40ea-968b-7a68a13c91ac.png">

**Comment by pangh-space** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by jxljf** [comment]
https://github.com/AliyunContainerService/k8s-for-docker-desktop/issues/180 与这个重复
