### ISSUE TITLE
问一下,没有v.1.24.2分支吗？

### ISSUE THREAD

**Issue by siyecoo** [AliyunContainerService/k8s-for-docker-desktop#203]
git checkout v1.24.0  please error: pathspec 'v1.24.0' did not match any file(s) known to git

是没有该分支吗？为什么md里面写着可以切换

**Comment by zuohl** [comment]
同问

**Comment by AYngKi** [comment]
同问

**Comment by zitongchen** [comment]
要支持 Kubernetes v1.24.2 只需要拉取 k8s-for-docker-desktop 项目 master 分支，并修改该项目根目录的 `images.properties` 文件，将 Kubernetes 的版本号改为 1.24.2 即可。

![image](https://user-images.githubusercontent.com/12184118/186703387-11889791-43f0-45da-84cc-f07bae060399.png)

**Comment by zxxf18** [comment]
1、清理镜像
2、  
Docker Engine 中配置代理
```
"registry-mirrors": [
    "https://docker.mirrors.ustc.edu.cn",
    "https://cr.console.aliyun.com/"
 ]
```
3、重启docker会自动下载对应版本并启动

**Comment by siyecoo** [comment]
> 1、清理镜像 2、 Docker Engine 中配置代理
> 
> ```
> "registry-mirrors": [
>     "https://docker.mirrors.ustc.edu.cn",
>     "https://cr.console.aliyun.com/"
>  ]
> ```
> 
> 3、重启docker会自动下载对应版本并启动

我试了4-5个加速镜像代理了 没用 下不动 ,不知道是不是我mac问题 每次至少等30分钟以上 还是下载不完

**Comment by zxxf18** [comment]
我刚用这个，大概7、8min装完

**Comment by khs1994** [comment]
现在国内可以直接开启了吧

**Comment by geffzhang** [comment]
Docker Desktop 可以直接启用Kubernetes 1.25 了
https://www.cnblogs.com/shanyou/p/16770868.html

**Comment by dappbujiujiu** [comment]
> 我刚用这个，大概7、8min装完

为此我连desktop都重新下载安装一遍，然后照此start 目前也20分钟了。。。主要不知道怎么看卡在哪个环节

**Comment by denverdino** [comment]
已更新，如果镜像拉取没有问题，可以忽略相关步骤。
