### ISSUE TITLE
not exits v1.25.0 branch

### ISSUE THREAD

**Issue by pyygithub** [AliyunContainerService/k8s-for-docker-desktop#209]

**Comment by geffzhang** [comment]
Docker Desktop 可以直接启用Kubernetes 1.25 了
https://www.cnblogs.com/shanyou/p/16770868.html

**Comment by abadm** [comment]
> Docker Desktop 可以直接启用Kubernetes 1.25 了 https://www.cnblogs.com/shanyou/p/16770868.html

直接启用就行，后面步骤还是那一套 [配置 Kubernetes 控制台](https://github.com/AliyunContainerService/k8s-for-docker-desktop#配置-kubernetes-控制台)

**Comment by denverdino** [comment]
已更新，如果镜像拉取没有问题，可以忽略相关步骤。
