### ISSUE TITLE
docker for win 2.0.3.x是不是不行

### ISSUE THREAD

**Issue by hailianglone** [AliyunContainerService/k8s-for-docker-desktop#21]

**Comment by hailianglone** [comment]
vpnkit.exe: tcp:127.0.0.1:6445:tcp:127.0.0.1:6443 proxy failed with flow proxy a: attempted to write to a closed flow

windows10 
![1552448185(1)](https://user-images.githubusercontent.com/23262369/54252024-4361e700-4584-11e9-99a7-935f24f1dc88.png)

**Comment by denverdino** [comment]
用master分支不行吗？

**Comment by hailianglone** [comment]
不行呢。

**Comment by hailianglone** [comment]
镜像可以下载。但是k8s启动不了.正在下2.0.1.x版本

**Comment by hailianglone** [comment]
切换2.0.1.x已经可以

**Comment by sheng-jie** [comment]
遇到同样的问题。

**Comment by denverdino** [comment]
Mac是可以的，周末我看看Windows
![image](https://user-images.githubusercontent.com/409721/54414381-e6a52e80-4733-11e9-87f6-6c3c4663a4a7.png)

**Comment by lluck42** [comment]
看来还是用 desktop 的比较多，minikube 那边才到 v0.30

**Comment by sheng-jie** [comment]
已经解决了，未仔细看说明。切换到v2.0.0.2版本就好了，git clone本项目后，`git checkout v2.0.0.2`切换分支后，再执行` .\load_images.ps1`就可以了。

**Comment by hailianglone** [comment]
> 已经解决了，未仔细看说明。切换到v2.0.0.2版本就好了，git clone本项目后，`git checkout v2.0.0.2`切换分支后，再执行` .\load_images.ps1`就可以了。

你确认？windows ？ 我说的是2.0.3.x不是2.0.0.3

**Comment by hailianglone** [comment]
> Mac是可以的，周末我看看Windows
> ![image](https://user-images.githubusercontent.com/409721/54414381-e6a52e80-4733-11e9-87f6-6c3c4663a4a7.png)

windows 也可以？
