### ISSUE TITLE
现在的版本是v1.25.2

### ISSUE THREAD

**Issue by xuzequn** [AliyunContainerService/k8s-for-docker-desktop#212]
新安装一个docker- desktop， kubernetes的版本是v1.25.2。 改了一下v1.25.0分支的版本好，将.0改成.2。结果也没有启动kuberntes。猜测是版本号不对。希望更新v1.25.2版本。

**Comment by megatronyy** [comment]
我也是这样改的，也失败了

**Comment by mytulips** [comment]
修改一下images.properties文件里面的版本号就可以了，我这边已经正常启动k8了。
k8s.gcr.io/pause:3.8=registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.8
k8s.gcr.io/kube-controller-manager:v1.25.2=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.25.2
k8s.gcr.io/kube-scheduler:v1.25.2=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.25.2
k8s.gcr.io/kube-proxy:v1.25.2=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.25.2
k8s.gcr.io/kube-apiserver:v1.25.2=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.25.2
k8s.gcr.io/etcd:3.5.4-0=registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.5.4-0
k8s.gcr.io/coredns:v1.9.3=registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:v1.9.3
k8s.gcr.io/ingress-nginx/controller:v1.2.1=registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v1.2.1
k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.2.2=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-webhook-certgen:v1.2.2

**Comment by denverdino** [comment]
Merged
