### ISSUE TITLE
启动失败，报连接"http://ipc/kubernetes/start"超时

### ISSUE THREAD

**Issue by yuanwence** [AliyunContainerService/k8s-for-docker-desktop#216]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/104064882/200252477-3c4648f2-c853-4458-8e97-22a5034e1ab4.png">
Windows版本：win11 pro 2022H2
docker版本：4.13.1
Kubernetes: v1.25.2

注：之前4.12安装并启动成功了，结果重启计算机后，docker自己升级到4.13.1了，更新git上的最新脚本升级后，就一直提示失败了，刚刚重装系统也无用。
http://ipc/kubernetes/start
看着这个ipc不是真实域名，自己映射host到本地也不行

**Comment by yuanwence** [comment]
附带一个问题：
最新版本中C:\ProgramData\DockerDesktop\下没有找到pri文件夹，
不过C:\Users\yourUserName\AppData\Local\Docker\pki找到了
不知道是不是最新版本文件结构变了

**Comment by yuanwence** [comment]
找到问题原因了，我说一下分析与解决过程，你们要是遇到了可以参考一下
1、之前在公司用的电信的宽带，用的4.12.0版本的的docker。当时是可以启动成功的。
这几天居家办公（都是用的自己的电脑），在家用的移动的宽带，初始我以为是自动升级造成的。 降级docker也不行，重装系统装旧版本的docker也不行。
2、最后瞄准了网络问题，联想到之前有过，一些网站，联通（老家）能访问，移动（现住地）访问不了的情况。
我尝试切换到我的联通流量的热点，等待几十秒后连接成功了。
新旧版本都试过了，都能成功

解决方法：切换到联通或电信的网络，或者一些更科学的方法

**Comment by denverdino** [comment]
Docker Hub 最近感觉访问非常不稳定，可以试着手工pull Docker镜像
docker pull docker/desktop-vpnkit-controller:v2.0
docker pull docker/desktop-storage-provisioner:v2.0
docker pull docker/desktop-kubernetes:kubernetes-v1.25.2-cni-v1.1.1-critools-v1.24.2-cri-dockerd-v0.2.5-1-debian
