### ISSUE TITLE
error: pathspec 'v1.25.2' did not match any file(s) known to git

### ISSUE THREAD

**Issue by chenyunshan** [AliyunContainerService/k8s-for-docker-desktop#218]
error: pathspec 'v1.25.2' did not match any file(s) known to git

**Comment by chenyunshan** [comment]
remotes/origin/v1.21.3
  remotes/origin/v1.21.4
  remotes/origin/v1.21.5
  remotes/origin/v1.22.4
  remotes/origin/v1.22.5
  remotes/origin/v1.23.4
  remotes/origin/v1.24.0
  remotes/origin/v1.24.2
  remotes/origin/v1.25.0
  remotes/origin/v2.0.0.2
  remotes/origin/v2.0.1.0

**Comment by denverdino** [comment]
Fixed
