### ISSUE TITLE
请教 2.0.0.3 stable 版本 切换到2.0.0.2也是一直停留在starting ! 有解么

### ISSUE THREAD

**Issue by xmw1992** [AliyunContainerService/k8s-for-docker-desktop#22]

**Comment by denverdino** [comment]
Docker Desktop for Windows 2.0.0.3 stable  使用 2.0.0.2 分支没有问题，可以正常启动

**Comment by xmw1992** [comment]
好 我再尝试一下，我本机的某些配置会有影响么？

**Comment by xmw1992** [comment]
尝试过了,还是不行啊！哎

**Comment by denverdino** [comment]
是否配置了Docker Engine镜像代理？有些需要从Docker Hub拉取

**Comment by xmw1992** [comment]
您好， 只配置了这个镜像 http://registry.docker-cn.com；  docker  Mac Version 2.0.0.3 (31259)stable   
使用docker images 查看 该下载的镜像文件都下载了    docker ---> Cgroup Driver: cgroupfs   kubectl 这个的没看到
我在ketematic上面看有报一些错误

**Comment by denverdino** [comment]
如果有错误信息可以贴一下

**Comment by xmw1992** [comment]
镜像无法启动 报错 etcdmain: listen tcp 220.250.64.26:2380: bind: cannot assign requested address

**Comment by xmw1992** [comment]
<img width="248" alt="021DD528-BD49-4EC3-A6E7-B7BF4FAB55C2" src="https://user-images.githubusercontent.com/24971434/54501542-dcb44300-4960-11e9-9f17-c8959f46fe48.png"> 这个是我手动启动的 有用么

**Comment by xmw1992** [comment]
可以了 跑起来了!!!!!!!!!!

**Comment by xmw1992** [comment]
感谢您的耐心指导😆
