### ISSUE TITLE
k8s一直starting

### ISSUE THREAD

**Issue by Jarnpher553** [AliyunContainerService/k8s-for-docker-desktop#23]
为什么我下了同一个版本的docker desktop v2.0.0.3，也下载了对应的k8s-for-docker-desktop，但是点击enable k8s，apply后，有一台是好的，但是另外一台怎么都starting状态，会存在哪些原因造成这种现象。

**Comment by denverdino** [comment]
是 2.0.0.2 branch吗？
如果配置正确，很多原因是虚拟机的网络配置导致的

**Comment by xiaods** [comment]
有一个技巧，看一下docker desktop日志就清楚了

```
pred='process matches ".*(ocker|vpnkit).*"
  || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
/usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
```

**Comment by Jarnpher553** [comment]
> 有一个技巧，看一下docker desktop日志就清楚了
> 
> ```
> pred='process matches ".*(ocker|vpnkit).*"
>   || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
> /usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
> ```

**Comment by Jarnpher553** [comment]
i have a try 我试试

**Comment by fengshi20102010** [comment]
> i have a try 我试试

亲，你解决了么 我也遇到了这个问题 mac 和 win 都是一样的

**Comment by Jarnpher553** [comment]
我解决了，看了docker日志文件，说是k8s的config文件无法保存修改，愿意是啥控制字符问题。于是我干脆直接把kube文件夹删了，然后重启k8s有自动生成了一个新的就好了……哈哈，你可以试试，我关闭问题啦

**Comment by ShaoHans** [comment]
> 有一个技巧，看一下docker desktop日志就清楚了
> 
> ```
> pred='process matches ".*(ocker|vpnkit).*"
>   || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
> /usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
> ```

请问这个要怎么执行？

**Comment by Jarnpher553** [comment]
> > 有一个技巧，看一下docker desktop日志就清楚了
> > ```
> > pred='process matches ".*(ocker|vpnkit).*"
> >   || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
> > /usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
> > ```
> 
> 请问这个要怎么执行？

如果是windows看日志的话直接在`C:\ProgramData\DockerDesktop`下的`service.txt打开就行了`
