### ISSUE TITLE
Docker Desktop 4.30.0  Kubernetes: v1.29.2  采用当前master版本下载镜像后，Kubernetes启动依然失败

### ISSUE THREAD

**Issue by wk4212** [AliyunContainerService/k8s-for-docker-desktop#238]
![图片](https://github.com/user-attachments/assets/d23c7d67-111c-443a-9f87-c7f407cc9182)

**Comment by pangh-space** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by jefferson-chern** [comment]
<img width="760" alt="image" src="https://github.com/user-attachments/assets/aa35501b-2bed-4fa5-aa63-97454e5c9493">
我这个也是一直失败，整了一天了，有大佬帮忙看看吗？也是k8s一直失败。刚开始是 k8s 一直在starting，后来就是 failed to start
<img width="478" alt="image" src="https://github.com/user-attachments/assets/cc88458d-fe5f-4be7-b605-e18eb71bfb3e">
 
<img width="289" alt="image" src="https://github.com/user-attachments/assets/40e88397-6182-43b4-a17c-10cf862df54a">

**Comment by yelijing18** [comment]
Docker Desktop 运行 Kubernetes 还需要额外的 Docker 镜像，参考：https://github.com/docker/for-win/issues/6820
一共是下面这三个，版本号与具体的 Kubernetes 版本有关（这是 v1.29.2的）：
```
docker/desktop-kubernetes:kubernetes-v1.29.2-cni-v1.4.0-critools-v1.29.0-cri-dockerd-v0.3.11-1-debian
docker/desktop-vpnkit-controller:dc331cb22850be0cdd97c84a9cfecaf44a1afb6e
docker/desktop-storage-provisioner:v2.0
```
您可以自己挂个代理下载下来就能使用了。

**Comment by denverdino** [comment]
最新的版本已经包含相关镜像同步
