### ISSUE TITLE
macOS v2.0.0.2 doesn't work

### ISSUE THREAD

**Issue by HaiyuanZh** [AliyunContainerService/k8s-for-docker-desktop#26]
the last step ,when "enable kubernetes" , docker for mac will prompt "install kubernetes  cluster" which have 2 options cancel and ok, when cancel it will cancel the "enable",  when ok, docker will install kubernetes , the status always "Kubernetes is starting"

**Comment by denverdino** [comment]
参见 #23 
Mac查看Docker Desktop日志

```
pred='process matches ".*(ocker|vpnkit).*"
  || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
/usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
```


如果是windows看日志的话直接在C:\ProgramData\DockerDesktop下的service.txt打开就行了

**Comment by HaiyuanZh** [comment]
after enable kubernetes, the log shows:

**Comment by denverdino** [comment]
你配置HTTP proxy了吗？是否已经load了镜像。
有时候网络问题可以通过重启docker daemon完成

**Comment by qxl1231** [comment]
![image](https://user-images.githubusercontent.com/8305742/55937776-67404780-5c6c-11e9-95f4-32837106a31d.png)
我也是,只要点enable, 直接就去安装,我不想它去安装,我已经./loadimage 过了,但是它一直自动去安装?

**Comment by HaiyuanZh** [comment]
After many many times of retry, reset to factory..., finally, it works.
<img width="495" alt="image" src="https://user-images.githubusercontent.com/16501631/56074952-481cf380-5ded-11e9-8c4f-3e8cdbff13ea.png">

I think the reason is that my proxy has to be closed, then totally follow the steps.

**Comment by ruanjiehui** [comment]
> after enable kubernetes, the log shows:
> ... repeating
> 
> ```
> 2019-03-27 12:39:08.652986+0800  localhost com.docker.vpnkit[92105]: HTTP proxy --> 64.233.189.82:443 Host:k8s.gcr.io:443 (Origin): CONNECT
> 2019-03-27 12:39:09.018210+0800  localhost com.docker.driver.amd64-linux[92106]: (libsystem_info.dylib) [com.apple.network.libinfo:si_destination_compare] no preference, equal min rtt 0.218750
> 2019-03-27 12:39:09.018283+0800  localhost com.docker.driver.amd64-linux[92106]: (libsystem_info.dylib) [com.apple.network.libinfo:si_destination_compare] Rule 6, prefer d2, d2 precedence 50 > d1 precedence 35
> 2019-03-27 12:39:09.018344+0800  localhost com.docker.driver.amd64-linux[92106]: (libsystem_info.dylib) [com.apple.network.libinfo:si_destination_compare] <private>@0 < <private>@0
> 2019-03-27 12:39:09.019882+0800  localhost com.docker.driver.amd64-linux[92106]: Cannot list nodes: Get https://localhost:6443/api/v1/nodes: EOF
> 2019-03-27 12:39:10.016640+0800  localhost com.docker.driver.amd64-linux[92106]: (libsystem_info.dylib) [com.apple.network.libinfo:si_destination_compare] no preference, equal min rtt 0.218750
> 2019-03-27 12:39:10.016682+0800  localhost com.docker.driver.amd64-linux[92106]: (libsystem_info.dylib) [com.apple.network.libinfo:si_destination_compare] Rule 6, prefer d2, d2 precedence 50 > d1 precedence 35
> 2019-03-27 12:39:10.016707+0800  localhost com.docker.driver.amd64-linux[92106]: (libsystem_info.dylib) [com.apple.network.libinfo:si_destination_compare] <private>@0 < <private>@0
> 2019-03-27 12:39:10.018427+0800  localhost com.docker.driver.amd64-linux[92106]: Cannot list nodes: Get https://localhost:6443/api/v1/nodes: EOF
> ```
> any suggestions?

I have the same question.

**Comment by HaiyuanZh** [comment]
@ruanjiehui 
For me, I turned off my proxy ( ss ).

**Comment by HaiyuanZh** [comment]
@ruanjiehui

**Comment by HaiyuanZh** [comment]
@ruanjiehui 
For me , I think I did 2 key actions:
1: turn off my proxy ( ss ), totally exit it.
2: delete the dns that inputed by myself (such as 8.8.8.8 ) , use the default dns from router, that's for  "nslookup localhost" command should return correctly.

then follow the readme steps.  good luck.

by the way , before enable kubernetes, delete the ~/.kube path. after enable and apply, you have to wait about several minutes depend your network speed.

**Comment by ruanjiehui** [comment]
> @ruanjiehui
> For me , I think I did 2 key actions:
> 1: turn off my proxy ( ss ), totally exit it.
> 2: delete the dns that inputed by myself (such as 8.8.8.8 ) , use the default dns from router, that's for "nslookup localhost" command should return correctly.
> 
> then follow the readme steps. good luck.
> 
> by the way , before enable kubernetes, delete the ~/.kube path. after enable and apply, you have to wait about several minutes depend your network speed.

Thanks for your idea,this is the problem which make k8s always starting.
![image](https://user-images.githubusercontent.com/9566149/56371177-32655f00-622f-11e9-974c-cd9ca7424509.png)

**Comment by YongyouCloud** [comment]
> the last step ,when "enable kubernetes" , docker for mac will prompt "install kubernetes cluster" which have 2 options cancel and ok, when cancel it will cancel the "enable", when ok, docker will install kubernetes , the status always "Kubernetes is starting"

你git checkout v2.0.0.2了吗
