### ISSUE TITLE
最新的docker已经是2.0.0.3,有对应的分支吗

### ISSUE THREAD

**Issue by qxl1231** [AliyunContainerService/k8s-for-docker-desktop#30]
目前的2.0.0.2已经不适用了,我如何修改images

**Comment by qxl1231** [comment]
![image](https://user-images.githubusercontent.com/8305742/55941102-1df3f600-5c74-11e9-8a2c-721268dae204.png)
点击enable,一直在去install,而且获取不到东西,就卡死在那

**Comment by harry-wangx** [comment]
把master切换到v2.0.0.2,就可以了. 我昨天运行成功了.

**Comment by dreambo8563** [comment]
显示的 fail to start, 但实际上是部署成功的, 可以用
