### ISSUE TITLE
我找到一个更快安装k8s的办法,现在分享一下

### ISSUE THREAD

**Issue by qxl1231** [AliyunContainerService/k8s-for-docker-desktop#32]
https://github.com/qxl1231/2019-k8s-centos/blob/master/rancher-k8s-install.md

**Comment by pifuant** [comment]
@qxl1231 502 Bad Gateway

**Comment by xiaods** [comment]
这是使用rancher单机的部署方法，和k8s-for-docker-destop的目的不一样。 ignore.

**Comment by xutingyin** [comment]
在 powershell 中执行  curl -kL http://localhost/apple 
出现 
`Invoke-WebRequest : 找不到与参数名称“kL”匹配的参数。
所在位置 行:1 字符: 6
+ curl -kL http://localhost/apple
+      ~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest]，ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`


又换到Git bash 里面执行 ，报：
`curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused`

请问有遇到同样问题的？麻烦告知一下，多谢了！

**Comment by xiaods** [comment]
out of date, please close it.

**Comment by denverdino** [comment]
@xiaods Thanks for notification
