### ISSUE TITLE
Docker desktop for win 2.0.4.1 k8s 一直处于starting

### ISSUE THREAD

**Issue by GuDuYing** [AliyunContainerService/k8s-for-docker-desktop#34]
k8s 版本号为：v1.14.1
service.txt输出的日志如下：
[Warning] time="2019-05-11T09:24:54+08:00" msg="Error while setting up kubernetes: cannot expose the external port: cannot connect to vpnkit: open \\\\.\\pipe\\dockerVpnKitControl: The system cannot find the file specified.. Retrying in 1s"

请问这是什么问题呢？

**Comment by kinjes** [comment]
try this
https://github.com/docker/for-win/issues/1962#issuecomment-431091114

**Comment by denverdino** [comment]
@kinjes 多谢！
也有可能是 docker/for-win/issues/3769
已经更新README.md
