### ISSUE TITLE
怎么不同步 k8s 仓库更新了？

### ISSUE THREAD

**Issue by gumutianqi** [AliyunContainerService/k8s-for-docker-desktop#4]

**Comment by denverdino** [comment]
Details?

**Comment by gumutianqi** [comment]
镜像还是：v1.10.3，已经有 v1.13.0 的更新了

**Comment by denverdino** [comment]
Docker for Desktop 是 1.10.3版本

如需 1.13.0 可以看一下  https://cr.console.aliyun.com/images/cn-hangzhou/google_containers/kube-apiserver/detail

registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver

多谢

**Comment by gumutianqi** [comment]
了解，这个版本目前和Docker for Desktop保持一致
