### ISSUE TITLE
安装Ingress 时报 404

### ISSUE THREAD

**Issue by heyixiaoran** [AliyunContainerService/k8s-for-docker-desktop#46]
执行kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/provider/cloud-generic.yaml
时，报404错误，error: unable to read URL "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/provider/cloud-generic.yaml", server reported 404 Not Found, status code=404

是改地址了还是怎样？

**Comment by zy84338719** [comment]
> 执行kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/provider/cloud-generic.yaml
> 时，报404错误，error: unable to read URL "https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/provider/cloud-generic.yaml", server reported 404 Not Found, status code=404
> 
> 是改地址了还是怎样？
用这个地址
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud-generic.yaml

**Comment by heyixiaoran** [comment]
谢大神指导，感谢
