### ISSUE TITLE
No such image: registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:0.25.1

### ISSUE THREAD

**Issue by lyling** [AliyunContainerService/k8s-for-docker-desktop#49]
Error response from daemon: No such image: registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:0.25.1
Error: No such image: registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:0.25.1

**Comment by denverdino** [comment]
I cannot recreate the issue. Pls double check.
