### ISSUE TITLE
docker desktop k8s v1.14.7 released

### ISSUE THREAD

**Issue by wuyongdec** [AliyunContainerService/k8s-for-docker-desktop#51]
Hope new branch v1.14.7 will be updated soon~

**Comment by denverdino** [comment]
Which version?

And PR are welcom, you can modify this file 

https://github.com/AliyunContainerService/k8s-for-docker-desktop/blob/master/images.properties

**Comment by yidasanqian** [comment]
@denverdino Could you new a branch v1.14.7? I can new a PR.

**Comment by denverdino** [comment]
1.14.7 branch is created, pls submit your PR. thanks a lot
