### ISSUE TITLE
Kubernetes cluster installation 19.03.4

### ISSUE THREAD

**Issue by ghd258** [AliyunContainerService/k8s-for-docker-desktop#55]
![QQ图片20191024171417](https://user-images.githubusercontent.com/4811375/67475932-a58dd900-f689-11e9-8e41-951e40283c7e.png)

The initial Kubernetes cluster installation takes a few minutes and requires an Internet connection.

Install the Kubernetes cluster now?
这个是必须安装才能往下走，
![QQ图片20191024181210](https://user-images.githubusercontent.com/4811375/67476076-dff77600-f689-11e9-8b00-871b8ecc942b.png)

**Comment by denverdino** [comment]
没懂，是需求确认一下吗？

**Comment by ghd258** [comment]
docker环境里面安装启用k8s无法成功，第一个图的那个安装进度条会安装中 无法完成

**Comment by denverdino** [comment]
Fixed in 1.14.7 branch
