### ISSUE TITLE
运行./load_images.sh 时报错

### ISSUE THREAD

**Issue by renhaixiang** [AliyunContainerService/k8s-for-docker-desktop#58]
bash shell 运行./load_images.sh 出现错误 invalid reference farmat
错误如下：
`$ ./load_images.sh
images.properties found.
invalid reference format
Error parsing reference: "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.1\r" is not a valid repository/tag: invalid reference format
Error response from daemon: invalid reference format
invalid reference format
Error parsing reference: "registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.15.4\r" is not a valid repository/tag: invalid reference format
Error response from daemon: invalid reference format
invalid reference format
Error parsing reference: "registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.15.4\r" is not a valid repository/tag: invalid reference format
Error response from daemon: invalid reference format
invalid reference format
Error parsing reference: "registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.15.4\r" is not a valid repository/tag: invalid reference format
Error response from daemon: invalid reference format
invalid reference format
Error parsing reference: "registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.3.10\r" is not a valid repository/tag: invalid reference format
Error response from daemon: invalid reference format
invalid reference format
Error parsing reference: "registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:1.3.1\r" is not a valid repository/tag: invalid reference format
Error response from daemon: invalid reference format
invalid reference format
Error parsing reference: "registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetes-dashboard-amd64:v1.10.1\r" is not a valid repository/tag: invalid reference format
Error response from daemon: invalid reference format
invalid reference format
Error parsing reference: "registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:0.26.1\r" is not a valid repository/tag: invalid reference format
Error response from daemon: invalid reference format
`

**Comment by denverdino** [comment]
您是用windows吧，

试着用一下 dos2unix 转换 images.properties 

问题的根源是Git for Windows默认会将文本文件中的换行符强制转为DOS格式。这可以通过修改缺省设置 git config --global core.autocrlf false 再重新git clone项目来解决。但如果使用文本编辑器修改过文件，还是需要利用dos2unix转换修正换行符。

**Comment by renhaixiang** [comment]
@denverdino 首先，非常感谢！
当时我还纳闷怎么每个路径下都多了个换行“\r”，我还试着编辑images.properties，只留一个镜像源，结果发现仍然存在“\r”，原来是被强制转换了。
经过我删除后，修改缺省设置再重新git clone项目已解决问题。

**Comment by denverdino** [comment]
还有个方法， https://stackoverflow.com/questions/15520339/how-to-remove-carriage-return-and-newline-from-a-variable-in-shell-script/15520508

如果您验证过可以提一个PR，我手头没有Windows :-)

**Comment by renhaixiang** [comment]
已提PR @denverdino
