### ISSUE TITLE
windows10下启动需要执行 设置kubeconfig命令，不然集群起来之后会报Kubernetes on Windows Error: Unable to connect to the server: dial tcp [::1]:6445: connectex: No connection could be made because the target machine actively refused it的错误！

### ISSUE THREAD

**Issue by nicklv** [AliyunContainerService/k8s-for-docker-desktop#6]
管理员身份打开powershell，执行命令：
[Environment]::SetEnvironmentVariable("KUBECONFIG", $HOME + "\.kube\config", [EnvironmentVariableTarget]::Machine)

**Comment by denverdino** [comment]
hmm, I cannot recreate the issue. Not sure if you have multiple kube config file in your env. Thanks
