### ISSUE TITLE
怎么准确得到各版本dockerCE依赖的k8s版本

### ISSUE THREAD

**Issue by xbwzhoubotong** [AliyunContainerService/k8s-for-docker-desktop#68]
怎么得到各版本dockerCE依赖的k8s版本，包含其他的依赖？
比如 pause etcd 等？
谢谢

k8s.gcr.io/pause-amd64:3.1=registry.cn-hangzhou.aliyuncs.com/google_containers/pause-amd64:3.1
k8s.gcr.io/kube-controller-manager-amd64:v1.14.8=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager-amd64:v1.14.8
k8s.gcr.io/kube-scheduler-amd64:v1.14.8=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler-amd64:v1.14.8
k8s.gcr.io/kube-proxy-amd64:v1.14.8=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy-amd64:v1.14.8
k8s.gcr.io/kube-apiserver-amd64:v1.14.8=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver-amd64:v1.14.8
k8s.gcr.io/etcd-amd64:3.1.12=registry.cn-hangzhou.aliyuncs.com/google_containers/etcd-amd64:3.1.12
k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.8=registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-dns-sidecar-amd64:1.14.8
k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.8=registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-dns-kube-dns-amd64:1.14.8
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.8=registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.8
k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1=registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetes-dashboard-amd64:v1.10.1
quay.io/coreos/hyperkube:v1.7.6_coreos.0=registry.cn-hangzhou.aliyuncs.com/coreos_containers/hyperkube:v1.7.6_coreos.0
quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.21.0=registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:0.21.0

**Comment by denverdino** [comment]
请查看 Docker Desktop版本，Docker -> About Docker Desktop

**Comment by xbwzhoubotong** [comment]
这个是知道的，主要是除了 kube 开头的，还有 其他依赖，具体依赖的版本。
有没有日志或者命令输出，然后自己手工从 镜像上 pull 就可以

**Comment by denverdino** [comment]
en，可以先通过合适的网络环境测试一下，就可以拿到列表啦 :-)
