### ISSUE TITLE
Dashboard安装国内访问不到

### ISSUE THREAD

**Issue by 786744873** [AliyunContainerService/k8s-for-docker-desktop#69]
https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

**Comment by MetSystem** [comment]
error validating "kubernetes-dashboard.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
