### ISSUE TITLE
阿里云镜像地址换了？

### ISSUE THREAD

**Issue by wuyongdec** [AliyunContainerService/k8s-for-docker-desktop#71]
$ docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.1
Error response from daemon: Get https://registry.cn-hangzhou.aliyuncs.com/v2/: Moved Permanently

**Comment by denverdino** [comment]
没有啊，

$ docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.1
3.1: Pulling from google_containers/pause
Digest: sha256:759c3f0f6493093a9043cc813092290af69029699ade0e3dbe024e968fcb7cca
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.1
registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.1

**Comment by wuyongdec** [comment]
奇怪了，搞了半天都要报错误。。。

**Comment by xh4n3** [comment]
@wuyongdec 已经解决了吗？请问定位的原因是？
如果未解决，能否提供 docker 的日志和 curl -v https://registry.cn-hangzhou.aliyuncs.com/v2/ 的结果

**Comment by wuyongdec** [comment]
![image](https://user-images.githubusercontent.com/7280016/75853910-f678bf80-5e29-11ea-88b7-e77e61d29aaf.png)

**Comment by wuyongdec** [comment]
@xh4n3 没有解决

**Comment by wuyongdec** [comment]
<
{ [5 bytes data]
100    87  100    87    0     0     62      0  0:00:01  0:00:01 --:--:--   errors":[{"code":"UNAUTHORIZED","message":"authentication required","detaill}]}

* Connection #0 to host registry.cn-hangzhou.aliyuncs.com left intact

**Comment by xh4n3** [comment]
@wuyongdec 我在本地尝试了 ./load_images.sh 没有遇到异常，能否贴一下 docker info 的内容以及 docker 的日志？

**Comment by wuyongdec** [comment]
@xh4n3 问题解决了，我代理配错了，Sorry。

**Comment by gysqqsbxlqq** [comment]
> @xh4n3 问题解决了，我代理配错了，Sorry。

代理怎么配置的
