### ISSUE TITLE
6443拒接连接

### ISSUE THREAD

**Issue by kaiyangyang** [AliyunContainerService/k8s-for-docker-desktop#75]
Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it这个要怎么处理

**Comment by weetime** [comment]
6443 是宿主机端口吗  如果是宿主机 改成宿主机的ip

**Comment by ljh2057** [comment]
在局域网另一台 windows （已复制 config）上使用 kubectl 连接出现同样的错误

**Comment by denverdino** [comment]
应该只有本机可以访问，目前Docker Desktop不支持

参考 https://github.com/docker/for-mac/issues/3730

**Comment by ljh2057** [comment]
> 应该只有本机可以访问，目前Docker Desktop不支持
> 
> 参考 [docker/for-mac#3730](https://github.com/docker/for-mac/issues/3730)

嗯，确实是这个问题
