### ISSUE TITLE
Docker Desktop for Mac : Kubernetes is starting

### ISSUE THREAD

**Issue by Xphobia** [AliyunContainerService/k8s-for-docker-desktop#78]
Docker Desktop for Mac启用k8s后，一直显示 Kubernetes is starting，版本是匹配的，具体版本信息如下：

（1）Docker Desktop for Mac版本信息
![21587228425_ pic](https://user-images.githubusercontent.com/59901623/79643820-60c9a180-81d7-11ea-954c-fe1dc1e350de.jpg)

（2）load_images.sh拉取的k8s镜像版本
![31587229203_ pic](https://user-images.githubusercontent.com/59901623/79644080-31b42f80-81d9-11ea-9d74-42999238db77.jpg)

（3）k8s显示状态一直为starting
![41587229414_ pic](https://user-images.githubusercontent.com/59901623/79644148-9cfe0180-81d9-11ea-8755-f54837e35e57.jpg)

（4）k8s容器运行状态running
![51587229561_ pic_hd](https://user-images.githubusercontent.com/59901623/79644205-f6fec700-81d9-11ea-9521-d0c4137e2b8c.jpg)
 
  (5) 日志报错
        cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: EOF
![61587229693_ pic_hd](https://user-images.githubusercontent.com/59901623/79644254-4644f780-81da-11ea-9bef-e0481e9a4e1d.jpg)

**Comment by gaoxt** [comment]
这一步解决了我的问题：
> rm -rf ~/Library/Group\ Containers/group.com.docker/pki/

**Comment by StruggleYang** [comment]
> 这一步解决了我的问题：
> 
> > rm -rf ~/Library/Group\ Containers/group.com.docker/pki/
> > 重启k8s，耐心等待几分钟。

有效

**Comment by crazysunnylong** [comment]
> 这一步解决了我的问题：
> 
> > rm -rf ~/Library/Group\ Containers/group.com.docker/pki/
> > 重启k8s，耐心等待几分钟。

这个可以，有用。

**Comment by denverdino** [comment]
赞！

**Comment by denverdino** [comment]
19.03 is updated
