### ISSUE TITLE
curl -kL http://localhost/apple  执行失败

### ISSUE THREAD

**Issue by xutingyin** [AliyunContainerService/k8s-for-docker-desktop#79]
在 powershell 中执行  curl -kL http://localhost/apple 
出现 
`Invoke-WebRequest : 找不到与参数名称“kL”匹配的参数。`
`所在位置 行:1 字符: 6`
`+ curl -kL http://localhost/apple`
`+ CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest]，ParameterBindingException`
`+ FullyQualifiedErrorId : `NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

又换到Git bash 里面执行 ，报：
`curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused`

请问有遇到同样问题的？麻烦告知一下，多谢了！

**Comment by denverdino** [comment]
Windows的curl和Linux有所不同
可以试试
https://chocolatey.org/packages/curl
