### ISSUE TITLE
V1.15.5：kubectl create -f kubernetes-dashboard.yaml

### ISSUE THREAD

**Issue by wubiaowp** [AliyunContainerService/k8s-for-docker-desktop#82]
#### kubernetes-dashboard.yaml：
spec:
      containers:
      - name: kubernetes-dashboard
        image: registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetes-dashboard-amd64:v1.10.1

#### images.properties：
k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1=registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetes-dashboard-amd64:v1.10.1

#### update：
spec:
      containers:
      - name: kubernetes-dashboard
        image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1

**Comment by denverdino** [comment]
PR is welcome

**Comment by denverdino** [comment]
Closed by #83
