### ISSUE TITLE
docker for windows 搭建Kubernetes多个节点

### ISSUE THREAD

**Issue by xianyanglin** [AliyunContainerService/k8s-for-docker-desktop#84]
目前docker for windows搭建出来的只是Kubernetes单个节点，想要搭建Kubernetes集群，应该如何操作呢？

**Comment by denverdino** [comment]
这部分最好用vagrant之类的工具自己搭建，或者用阿里云

**Comment by jiguangxi** [comment]
> 这部分最好用vagrant之类的工具自己搭建，或者用阿里云

您好，请问使用多台windows机器  直接通过docker for windows是做不到的吗？  在网上找了两天了，感觉都是Linux环境下搭建集群，

**Comment by denverdino** [comment]
不能，多谢。可以考虑用阿里云容器服务 ACK 等云服务，支持Windows集群
