### ISSUE TITLE
win10 专业版 安装dashboard报错

### ISSUE THREAD

**Issue by ACEZOORO** [AliyunContainerService/k8s-for-docker-desktop#96]
执行：kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc5/aio/deploy/recommended.yaml
报错：Unable to connect to the server: dial tcp: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found.

**Comment by ChengLab** [comment]
我也遇到了，后来换成下面的安装命令可以了；kubectl create -f kubernetes-dashboard.yaml

**Comment by dirname** [comment]
这个大概率是运营商DNS的问题，可以翻墙试一下

**Comment by dirname** [comment]
或者修改 hosts
151.101.76.133  raw.githubusercontent.com

**Comment by ACEZOORO** [comment]
解决，版本更新导致

**Comment by 15192095633** [comment]
Unable to connect to the server: read tcp 192.168.1.110:57144->151.101.76.133:443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by 695648896** [comment]
> Unable to connect to the server: read tcp 192.168.1.110:57144->151.101.76.133:443: wsarecv: An existing connection was forcibly closed by the remote host.

你需要去查找raw.githubusercontent.com当前的ip地址，然后再去修改hosts
