### ISSUE TITLE
mac 使用desktop 部署的k8s启动pod报错问题

### ISSUE THREAD

**Issue by qixiang-liu** [AliyunContainerService/k8s-for-docker-desktop#98]
Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "pipeline-pipelines-controller-7f4bbcbcd5-rpssn": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"read init-p: connection reset by peer\"": unknown

**Comment by denverdino** [comment]
Fixed

**Comment by qixiang-liu** [comment]
什么意思，能帮忙解决下吗？

**Comment by qixiang-liu** [comment]
为啥直接给我closed了

**Comment by denverdino** [comment]
重新试一下吧，我更新了master分支的镜像列表

**Comment by qixiang-liu** [comment]
我还有个问题，就是我不知道如何去修改镜像版本。去改 kubeadm-config中的kubernetes-version吗？
